### ------------ DEV ------------

### GET color
GET http://localhost:3000/messages

### POST message
POST http://localhost:3000/messages HTTP/1.1 
Content-Type: application/json

{
  "household": {
    "name": "Smith",
    "color": "red"
  }
}


### ------------ PROD ------------

### GET color - HTTPS
GET https://buddy-lamp.onrender.com/messages

### POST message  - HTTPS
POST https://buddy-lamp.onrender.com/messages HTTP/1.1 
Content-Type: application/json

{
  "household": {
    "name": "Smith",
    "color": "blue"
  }
}